### ISSUE TITLE
Converting to self-contained standalone?

### ISSUE THREAD

**Issue by QuinnyPig** [eddiezane/lunchy#33]
I'm not much of a Ruby guy, but I was wondering how much work it would take to port this to something that could be installed via homebrew.

"brew install lunchy" will drive adoption in places that "gem install lunchy" will terrify people (namely: not ruby devs and who remember all too well the nightmare that CPAN wrought on systems). It doesn't seem that it would be too challenging, overall?

**Comment by fabn** [comment]
Is this dead? It would be so useful to have this as a global command a la `heroku`

**Comment by jamesgecko** [comment]
Lunchy has been available in [Homebrew's Cask repo](http://caskroom.io/) for a while.

**Comment by vladimyr** [comment]
> Lunchy has been available in [Homebrew's Cask repo](http://caskroom.io/) for a while.

[`lunchy-go`](https://github.com/sosedoff/lunchy-go) got migrated from Homebrew Cask to Homebrew  (https://github.com/Homebrew/homebrew-cask/pull/86101). Also, `lunchy` got added to Homebrew, so you can now install this project using:
```
brew install lunchy
```
or if you want to use [`lunchy-go`](https://github.com/Homebrew/homebrew-cask/pull/86101):
```
brew install lunchy-go
```
