### ISSUE TITLE
-bash: lunchy: command not found

### ISSUE THREAD

**Issue by jwstl** [eddiezane/lunchy#45]
I'm realitivly new to mac os, so this is probably a simple question. I have tried both gem install lunchy, and sudo gem install lunchy, with the same results.

running ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

Thanks,
Jason

**Comment by TyrelDenison** [comment]
I am having this issues as well, though I'm using zsh. Ruby 1.9.3-p448.
