### ISSUE TITLE
Services with partially common names

### ISSUE THREAD

**Issue by jphastings** [eddiezane/lunchy#48]
I cannot currently interact with the `couchdb` service because I have a `couchdb-lucene` service:

```
$> lunchy stop homebrew.mxcl.couchdb
Multiple daemons found matching 'homebrew.mxcl.couchdb'. You need to be more specific. Matches found are:
homebrew.mxcl.couchdb-lucene
homebrew.mxcl.couchdb
```

Can I suggest that if there is an exact match then it is assumed that is the one intended?

**Comment by eddiezane** [comment]
Close via #51
