### ISSUE TITLE
-bash: lunchy: command not found

### ISSUE THREAD

**Issue by shaunstanislaus** [eddiezane/lunchy#50]
i did 
    gem install lunchy

but command not found, my ruby version is below.
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
how do i resolve this ?

**Comment by erinbrown** [comment]
Are you using [rbenv](https://github.com/sstephenson/rbenv) to manage your rubies?  You may just have to run `rbenv rehash` to install shims for command-like executables like lunchy.

Details here: [rbenv rehash](https://github.com/sstephenson/rbenv#rbenv-rehash)

Hope this helps.

**Comment by eddiezane** [comment]
Did you manage to resolve this?

**Comment by shaunstanislaus** [comment]
nope, i didnt manage to resolve this.

**Comment by shaunstanislaus** [comment]
i did installed it via rbenv, i prefer rbenv.

but it is still not working.

**Comment by shaunstanislaus** [comment]
okay, lunchy is working after rehashing, thank you (:

**Comment by eddiezane** [comment]
Good to hear! This might be useful to you - https://github.com/sstephenson/rbenv-gem-rehash

**Comment by shaunstanislaus** [comment]
thank you! (:
