### ISSUE TITLE
Flag to install service from brew

### ISSUE THREAD

**Issue by eddiezane** [eddiezane/lunchy#64]
I've been doing `lunchy install -s $(brew --prefix redis)/*.plist` quite a bit recently. We should have a flag that will do this for a brew formula.

**Comment by bunnymatic** [comment]
Have you looked into the `brew service` thing (https://github.com/Homebrew/homebrew-services)?
it seems like about a year ago it was maybe going to go away, but there were checkins as recently as 1 month back.  Certainly that could take the place of `lunchy` and I wonder if it's a better route.  Not that I don't love `lunchy`.  I suppose I wonder about adding more code when it might be better to recommend - move to `homebrew-services`...

thoughts?

**Comment by bunnymatic** [comment]
on the other hand, the feature would be pretty straight forward... ;)

**Comment by eddiezane** [comment]
Good call. Didn't realize they broke it out. Can revisit if someone else has interest.
