### ISSUE TITLE
unable to start mysql even it says start

### ISSUE THREAD

**Issue by shaunstanislaus** [eddiezane/lunchy#65]
```bash
 ~ $ lunchy stop mysql
stopped homebrew.mxcl.mysql
 ~ $ lunchy start mysql
started homebrew.mxcl.mysql
 ~ $ mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (61)
~ $
```

**Comment by eddiezane** [comment]
Hmm I'm unable to replicate this. Anything else you could provide? Perhaps try adding the plist again?

```bash
~ lunchy install /usr/local/opt/mysql/*.plist
/usr/local/opt/mysql/homebrew.mxcl.mysql.plist installed to ~/Library/LaunchAgents
~ lunchy start mysql
started homebrew.mxcl.mysql
~ mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.6.26 Homebrew
```

**Comment by bunnymatic** [comment]
Has `mysql` in this machine worked before?  Are you sure your `mysql`
configuration is correct?

Lunchy is not terribly smart about whether the process actually
successfully started.  I might first verify that mysql starts up without
lunchy first.

You can try to manually start it

`mysql.server start`

If that gets mysql running, then maybe there is a problem with the plist
file that lunchy (and the Mac) are using to get things started.

**Comment by shaunstanislaus** [comment]
i fixed it. thank you (: in anycase how do i usually make use of lunchy to recognize a service to start, or rather how do i obtain or make a plist ?

**Comment by bunnymatic** [comment]
If you are using `homebrew`, most services come with a `.plist` file which
is a simple(ish) XML file that represents an Apple Property List.  Your
best bet is to follow the `homebrew` instructions to install their `plist`
into your user's launch set.  If you are not using `homebrew` for
installation, and the service you want to run does not come with it's own
`plist` specifications, you could try writing your own
https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/StartupItems.html.


To be clear, `lunchy` doesn't actually know about these `plist` files at
all.  It talks directly to `launchctl` and runs simple commands (like
`start`,`stop` etc).   So if you wanted to test a `plist`, you should
probably do that using the underlying `launchctl` command.  Once the
`plist` is working, you could use `lunchy` to install and manage the
service.

**Comment by shaunstanislaus** [comment]
Does lunchy work on Ubuntu?

**Comment by eddiezane** [comment]
At this time I think launchd and launchctl only run on OSX.

https://en.wikipedia.org/wiki/Launchd#Use_outside_OS_X

**Comment by bunnymatic** [comment]
Ubuntu (and most flavors of unix) already have a simpler way to start and
stop services.  More recent distros have a builtin helper called
`service`.  So you can simply call `service httpd restart` to restart the
webserver (or whatever... depending on the services you have on that box).

`lunchy` was built primarily because setting up service initialization
files and starting and stopping services on the Mac was *not* as simple as
on typical Unix machines.  I suspect, if OSX had followed the stop/start
service architecture as most flavors of Unix, we wouldn't have a need for
`lunchy`.

But they didn't... ;)

cheers
