### ISSUE TITLE
installed lunchy,zsh error occurred

### ISSUE THREAD

**Issue by gatspy** [eddiezane/lunchy#68]
error message:
complete:13: command not found: compdef
lunchy version: Lunchy 0.10.4
zsh version: zsh 5.0.5 (x86_64-apple-darwin14.0)

in ~/.zshrc ,add the following code
LUNCHY_DIR=$(dirname `gem which lunchy`)/../extras
if [ -f $LUNCHY_DIR/lunchy-completion.zsh ]; then
    . $LUNCHY_DIR/lunchy-completion.zsh
fi

**Comment by Edison-Hsu** [comment]
Add -U to Autoload
https://github.com/eddiezane/lunchy/issues/66
