### ISSUE TITLE
(Gem::LoadError)

### ISSUE THREAD

**Issue by dsharpen** [eddiezane/lunchy#70]
/Users/python/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'lunchy' (>= 0) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/var/root/.gem/ruby/2.2.0:/Users/python/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0', execute`gem env`for more information
    from /Users/python/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in`to_spec'
    from /Users/python/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
    from /Users/python/.rvm/gems/ruby-2.2.0/bin/lunchy:22:in`<main>'
    from /Users/python/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/python/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in`<main>'

**Comment by iamarmanjon** [comment]
Did you try reinstalling the gem? `gem uninstall lunchy`?
