### ISSUE TITLE
Issue with similarly named scripts

### ISSUE THREAD

**Issue by keith** [eddiezane/lunchy#71]
Currently if you have a launchd script named `foo` and one named `foo.bar`, you cannot enable `foo`. Instead you get an error from [here](https://github.com/eddiezane/lunchy/blob/c78e554b60e408449937893b3054338411af273f/lib/lunchy.rb#L140-L141). This looks to be caused by not checking for more specific matches, rather than just the regex matches.

I'm happy to submit a patch to also do a check for equality, besides just regex, if you're open to it!

**Comment by eddiezane** [comment]
@keith, always love contributions! Thanks for digging and offering.

**Comment by keith** [comment]
Ah. I just discovered the `--exact` flag, which also solves this problem.

**Comment by keith** [comment]
I think we should defer to people to using that flag to solve this problem instead. Sorry for the noise!
