### ISSUE TITLE
Quick Curiosity/Discussion on — lunchy install [file]

### ISSUE THREAD

**Issue by salomoko** [eddiezane/lunchy#72]
_Apologize, but 140 chars (twitter) wasn't enough to write my question..._
@mperham / @eddiezane can you provide a quick confirmation for me?

`lunchy install [file]` does what exactly? seems to me https://github.com/eddiezane/lunchy/blob/master/lib/lunchy.rb#L55-L69 it either sym links or copies an agents plist file to either the users ~/Library/LaunchAgent or the systems /Library/LaunchAgent directory? Essentially a convenience method that does [Step 6 in this how-to article](https://kyezra.co/2mqTQgA)??
Although, while researching where the `CONFIG[:symlink]` constant hash was defined I came across this comment (https://github.com/eddiezane/lunchy/blob/master/bin/lunchy#L48), which pretty much answers my question (I think)?

However, in what instances would I use this method? Perhaps if I compile and install from source a service? Is it simply what I referenced in that postgres article? A convenience method for `cp`? 
Can you provide a [file] arg example where I would need Lunchy install? (_I'd like to get apache2 deamonized and managed through Lunchy!_) Guess that would involve writing a wrapper around `apachectl` amirite?

Btw. I love this little tool! Agree, odd name but whatevs! It's fuckin handy!

**Comment by eddiezane** [comment]
Hey @salomoko,

On macOS services managed by `launchd` need to live in specific directories depending on who is to run the service and when it is to start. There's a great chart [here](http://www.launchd.info/). This is why the `install` command exists in `lunchy`. Depending on your need, you'd either copy the plist or symlink it to have changes reflected from a source.

If you're using [Homebrew](https://brew.sh/) on your Mac I'd highly recommend checking out [brew services](https://github.com/Homebrew/homebrew-services) which has a great `launchctl` implementation for anything installed via Homebrew. I currently only use `lunchy` to manage services developed locally or not installed through brew.

Let me know if you have any other questions!
