### ISSUE TITLE
Proposal: Change `master` branch to `main`

### ISSUE THREAD

**Issue by bunnymatic** [eddiezane/lunchy#75]
Github and others have started moving away from `master` as the default branch name in favor of `main`.

I'd like to propose that we move this repo to follow this as well.

I'd submit a PR, but I believe this is more of a Github repo settings change.

**Comment by eddiezane** [comment]
Totally support this.

Looks like I just need to flip this once the branch exists.

![image](https://user-images.githubusercontent.com/959573/92663785-768f4e80-f2bf-11ea-82a1-b2d61221da1e.png)

Let's just make sure that doing so doesn't break homebrew or anything else.

**Comment by bunnymatic** [comment]
Yep.  I think that should be it.  I'm curious - where is the homebrew connection?  do you control your homebrew entry?  or is do you make a new PR for that?

**Comment by eddiezane** [comment]
This is done. GitHub updated their tooling to handle all the things. https://github.com/github/renaming#renaming-existing-branches

Folks visiting the repo will be alerted to run these commands.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
